GET https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1m&limit=1

###
GET https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT

###
GET https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT&startTime=1741152648000